[package]
name = "password_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-crypto = "0.2.36"
hex = "0.4"
rand = "0.8"
sha2 = "0.10.8"
rusqlite = "0.32.1"
egui = "0.28.1"
eframe = "0.28.1"
winapi = { version = "0.3", features = ["winuser"] }
clipboard = "0.5"